"""
Django settings for arkwithsite project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print("BASE_DIR :[%s]" % BASE_DIR)
#os.getcwd()
#os.chdir(path)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oa8@#pxvd01mz2who4r8nvc2g^swaeua1nm0dgpbgs6p!65c&!'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
# 윈도우 개발 환경에서 실행시는 DEBUG = True로 해야 static디렉토리 아래 리소스가 적용됨
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'chatapp.apps.ChatappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arkwithsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': ['django.contrib.staticfiles.templatetags.staticfiles'],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arkwithsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
# in linux
#STATIC_ROOT = '/home/ubuntu/arkwithsite/static'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = ''

STATIC_URL = '/static/'
# STATICFILES_DIRS = ( os.path.join('static'), )

# in Windows
# STATIC_ROOT = ''

# STATIC_URL = '/static/'

# STATICFILES_DIRS = ( os.path.join('static'), )

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {                        # message 출력 포맷 형식
#         'verbose': {
#             'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             'datefmt' : "%d/%b/%Y %H:%M:%S"
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },
#     'handlers': {
#         # console logs to stderr
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs/arkwithsite.log'),
#             'when': 'D', # this specifies the interval
#             'interval': 1, # defaults to 1, only necessary for other values 
#             'backupCount': 20, # how many backup file to keep, 10 days
#             'formatter': 'verbose',
#             'encoding': 'utf-8' #로그 파일에서 한글 깨지믄 문제 해결을 위해
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers':['console', 'file'],
#             'propagate': True,
#             'level':'DEBUG',
#         },
#         'django.request': {
#             'handlers':['file'],
#             'propagate': False,
#             'level':'DEBUG', }, 

#         'chatapp': {                   # Project에서 생성한 app의 이름
#             'handlers': ['console', 'file'],      # 다른 app을 생성 후 해당 app에서도
#             'propagate': False,
#             'level': 'DEBUG',          # 사용하고자 할 경우 해당 app 이름으로
#         },                             # 좌측 코드를 추가 작성해서 사용
#     }
# }
# print("Initializing LOGGING in settings.py - if you see this more than once use 'runserver --noreload'")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = 'arkwith7@gmail.com'
EMAIL_HOST_PASSWORD = '{dkzmdnlem}'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER